### PR TITLE
Add limit option to duplicate url-loader behaviour

### PR DESCRIPTION
**Pull request by dfournier**
`url-loader` webpack loader inlines content instead of copying the file. The optimisation is made only for file size under a limit. By setting this limit to 0 by default, there is no breaking.

### CODE REVIEW

**Comment by sheerun** [comment]
Thank you for PR, it looks fine to me. Could you:
- remove yarn.lock?
- still mention file-loader? (i.e. it is similar to combined file-loader and url-loader)

**Comment by dfournier** [comment]
I agree with both comments. `url-loader` should be mentioned only next to the `limit` option.

**Comment by dfournier** [comment]
Actually, I have a question about `yarn.lock`. Do you want me to remove the file entirely or just what I changed?

**Comment by sheerun** [comment]
oh, sorry I didn't see it was already present. I'll test and merge this PR this week :)

**Comment by dfournier** [comment]
I put it back then 😅

**Comment by dfournier** [comment]
Hi!

Sorry to annoy you with this PR but do you consider merging and releasing it? I'm asking to know if it worth it to push on `npm` a fork of your library with my 2 PRs merged. Now I'm referencing a branch and it's not ideal.

Best

**Comment by sheerun** [comment]
sorry about that, releasing :)

**Pull request merged**
