### PR TITLE
Plugin refresh and support of node_modules imports

### PR DESCRIPTION
**Pull request by idangozlan**
- Fixed problem of non-parsing node_modules imported files (https://github.com/sheerun/babel-plugin-file-loader/issues/8)
- Upgraded versions to remove security breaches
- Changed Chai + Mocha to Jest for better testing and snapshots
- Migrated CircleCI's config to 2.0
- Lint: now the project is linted with airbnb-base standard

### CODE REVIEW

**Comment by eugef** [comment]
Any plans to merge this PR?

**Comment by sheerun** [comment]
I've pushed most of changes covered by this PR to master:

- Upgaded versions
- Changed to Jest via modern-node
- Added snapshot testing
- Migrated to travis.ci
- Linting with standard

The only non-implemented thing is "Fixed problem of non-parsing node_modules imported files (#8)" but it would need to be re-written on top of what's in master.

**Comment by eugef** [comment]
Actually i am interested exactly in the fix for #8

**Comment by sheerun** [comment]
I can't fix this unless I can reproduce it, please see #8 

This PR introduces far more changes than necessary to fix this issue and no tests or changes in example project that show the issue. If you want me to fix this, please modify example project so I can reproduce the issue on my computer

**Pull request closed without merging**
